name: WebLeaderBoard
description: "A leaderboard plugin that shows player statistics on a website."
author: ItsMax123

main: Max\WebLeaderBoard\Main
version: 1.0.0
api: 3.0.0

commands:
  webleaderboard:
    description: Sends the link for the WebLeaderBoard website to the user.
    usage: "/webleaderboard"
    permission: webleaderboard.command

permissions:
  webleaderboard.command:
    description: Lets user use the webleaderboard command.
    default: true
